LOCAL_MODULE    := c
LOCAL_SRC_FILES := main.c
LOAD_C_FILES_DIR := capp/libs
SCREEN:=SCREEN_ORIENTATION_LANDSCAPE
versionName:=0.4
versionCode:=3
RUN_MODE:=so
WINDOW_FEATURE:=FLAG_FULLSCREEN
PACKAGE:=com.culosic.sdungeon2
APP_NAME:=S地牢-传承
versionCode:=2
